# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/7c/59a3248f411813f8ccba92a55feaac4bf360d29e2ff05ee7d8e1ef2d7dbf/MarkupSafe-2.1.3.tar.gz";
      sha256 = "1bfwpdm04zswg5lgw1kvc67sp95ib0wpi0kvfhdnzs3a5p9qwndg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "argparse" = super.buildPythonPackage rec {
    pname = "argparse";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl";
      sha256 = "0533cr5w14da8wdb2q4py6aizvbvsdbk3sj7m1jx9lwznvnlf5n3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "23.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f0/eb/fcb708c7bf5056045e9e98f62b93bd7467eb718b0202e7698eb11d66416c/attrs-23.1.0-py3-none-any.whl";
      sha256 = "012x6glahfkg28ncs726dcnbm76gib3j1861d8jv8byw5i9b8a0z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "autopep8" = super.buildPythonPackage rec {
    pname = "autopep8";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3c/24/4eadb64c81c10b354b0c2b6a54a3542c3ce112954cc4effff038beafb009/autopep8-2.0.2-py2.py3-none-any.whl";
      sha256 = "1wd2axyr91b3yzicgk78pzlr6a0v2q8zcpig5f3n10awbqxk1sc6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycodestyle"
      self."tomli"
    ];
  };
  "beautifulsoup4" = super.buildPythonPackage rec {
    pname = "beautifulsoup4";
    version = "4.12.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/f4/a69c20ee4f660081a7dedb1ac57f29be9378e04edfcb90c526b923d4bebc/beautifulsoup4-4.12.2-py3-none-any.whl";
      sha256 = "0jkxyp841grxb81rp44833nb90fihb24mm2k99li4zcx1p5209dx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."soupsieve"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2023.5.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/19/59961b522e6757f0c9097e4493fa906031b95b3ebe9360b2c3083561a6b4/certifi-2023.5.7-py3-none-any.whl";
      sha256 = "05n7h0lz1vh69hqlqi0vkygm74fx539gw5l93z5fysbqbj7ykhn6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.15.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2b/a8/050ab4f0c3d4c1b8aaa805f70e26e84d0e27004907c5b8ecc1d31815f92a/cffi-1.15.1.tar.gz";
      sha256 = "1y9lr651svbzf1m03s4lqbnbv2byx8f6f0ml7hjm24vvlfwvy06l";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/d7/8d757f8bd45be079d76309248845a04f09619a7b17d6dfc8c9ff6433cac2/charset-normalizer-3.1.0.tar.gz";
      sha256 = "1d89yl32j0c6i25zip73h5nq55jyxf2vyqxfg9crbsvhqgws5q1l";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "check50" = super.buildPythonPackage rec {
    pname = "check50";
    version = "3.3.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/e5/c80d24170fe49fdb03690d2d1cf523d5d90e814bb2725af83de559312309/check50-3.3.7-py3-none-any.whl";
      sha256 = "160yync775qnc43b3j61klca91q1nczswawsyc6d211gjd8dvlj4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."beautifulsoup4"
      self."jinja2"
      self."lib50"
      self."pexpect"
      self."pyyaml"
      self."requests"
      self."termcolor"
    ];
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "41.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/8c/47f061de65d1571210dc46436c14a0a4c260fd0f3eaf61ce9b9d445ce12f/cryptography-41.0.1.tar.gz";
      sha256 = "01hh79p08syjyihfh0i24khjlv3b9mixdxyjcabz9lq1ah47jifk";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "editorconfig" = super.buildPythonPackage rec {
    pname = "editorconfig";
    version = "0.12.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/04/e8a79c1db0c55ef03d53c05c61d06c4d6d3be37ef84e5400ce36b4a0fbe9/EditorConfig-0.12.3-py3-none-any.whl";
      sha256 = "1haj5r54qc96wllfgsz9csbbajmxmppf17kq2s5v0xd8b915223b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "icdiff" = super.buildPythonPackage rec {
    pname = "icdiff";
    version = "2.0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/11/542ff30f2c399d71126e55b64d41cb5caa78ddf7ce557fddf45607a41fe8/icdiff-2.0.6.tar.gz";
      sha256 = "16m72acv4fl6gvhqxralhgkd07x01am1wkn4fgy687k7blrknrx2";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl";
      sha256 = "1hn54ps4kgv2fmyvfaks38sgrvjc1cn4834sh7gadsx3x9wpxdwh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jellyfish" = super.buildPythonPackage rec {
    pname = "jellyfish";
    version = "0.11.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/0c/e3d16e03e209446cdd65107c05f47904e93b991a5b922d27cb36f2f97527/jellyfish-0.11.2.tar.gz";
      sha256 = "0nlc4pm4xyq734p22mjfkbmyciqzipwncpdx5527r4mr8cajnkv5";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "3.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl";
      sha256 = "0q9a30x046p3wvbgx598g4lmxwwykk0vjsjl21khx7r3zq5r7230";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "jsbeautifier" = super.buildPythonPackage rec {
    pname = "jsbeautifier";
    version = "1.14.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/ca/a0c5b01bb0f6a5aa38236023e23ab46fa80bde348b42eabba7f8b3ddc319/jsbeautifier-1.14.8.tar.gz";
      sha256 = "17wbz49qbn9dr64kxv6bj9261ig31dqm9glxzd51kmidliiy5i6l";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."editorconfig"
      self."six"
    ];
  };
  "lib50" = super.buildPythonPackage rec {
    pname = "lib50";
    version = "3.0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/29/27/fcdef6beb9b95e4db629c68158616cd5acd87be2d92deec3ff4bfa99a775/lib50-3.0.6-py3-none-any.whl";
      sha256 = "1gdjnfl8wv2pz419dr9bam67l4gpnl79jng35zy8cnsrvbp83jdm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."cryptography"
      self."jellyfish"
      self."pexpect"
      self."pyyaml"
      self."requests"
      self."termcolor"
    ];
  };
  "pexpect" = super.buildPythonPackage rec {
    pname = "pexpect";
    version = "4.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/7b/88dbb785881c28a102619d46423cb853b46dbccc70d3ac362d99773a78ce/pexpect-4.8.0-py2.py3-none-any.whl";
      sha256 = "0dq9f7irmml1nm9a2rx8dd6m2dqmzjj1x40mk0rg619wrdfsaj0b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
  };
  "ptyprocess" = super.buildPythonPackage rec {
    pname = "ptyprocess";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl";
      sha256 = "0dgg5x4nvdpfiz552diy11xg72y14s38hjz9qxygafnfgybg6hab";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycodestyle" = super.buildPythonPackage rec {
    pname = "pycodestyle";
    version = "2.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/54/001fdc0d69e8d0bb86c3423a6fa6dfada8cc26317c2635ab543e9ac411bd/pycodestyle-2.10.0-py2.py3-none-any.whl";
      sha256 = "0436f0anh63hshbjq907cbbrf9v0vg19ln5kv9dkkiwm0h6sykla";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.21";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl";
      sha256 = "1agwca0hgbpwmr9snhxafqjhfd52mq083rw5n7vf25amallm9r4f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-magic" = super.buildPythonPackage rec {
    pname = "python-magic";
    version = "0.4.27";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/73/9f872cb81fc5c3bb48f7227872c28975f998f3e7c2b1c16e95e6432bbb90/python_magic-0.4.27-py2.py3-none-any.whl";
      sha256 = "1lwl097if4wmsbf216gbjzzlh1fj4nixgr811nm01xq6sc59c4n2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz";
      sha256 = "18imkjacvpxfgg1lbpraqywx3j7hr5dv99d242byqvrh2jf53yv8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.31.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl";
      sha256 = "0gq02gh497vhifc00hvz1gpg5absfx8sgg05cpifcw0yq23j3kaq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "soupsieve" = super.buildPythonPackage rec {
    pname = "soupsieve";
    version = "2.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/37/673d6490efc51ec46d198c75903d99de59baffdd47aea3d071b80a9e4e89/soupsieve-2.4.1-py3-none-any.whl";
      sha256 = "1f7y8vvdvw0cvb9kmplcv087x8k5fcaqkj46fm2a6i4mh7kgw6qw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "style50" = super.buildPythonPackage rec {
    pname = "style50";
    version = "2.7.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dc/df/42f761f3bdce7e679ec4d4b8e7e696910694a734f7c4e177a49339872b75/style50-2.7.5-py3-none-any.whl";
      sha256 = "1w4qlpdjrpazv7fzwrjlxn7vvrgk8v2bagvkh7zqih9a1lg88vxl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."argparse"
      self."autopep8"
      self."icdiff"
      self."jinja2"
      self."jsbeautifier"
      self."python-magic"
      self."termcolor"
    ];
  };
  "submit50" = super.buildPythonPackage rec {
    pname = "submit50";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/17/07/2097bfc615cc4bc147e6e4dd59912458988693a25da211c7f186ff9dc990/submit50-3.1.1-py3-none-any.whl";
      sha256 = "1lkzms8vl8q62kx63xgshbsa7qy8azafbcr9mc1h7pcs7pjsi648";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."lib50"
      self."requests"
      self."termcolor"
    ];
  };
  "termcolor" = super.buildPythonPackage rec {
    pname = "termcolor";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/67/e1/434566ffce04448192369c1a282931cf4ae593e91907558eaecd2e9f2801/termcolor-2.3.0-py3-none-any.whl";
      sha256 = "0xflyyjsdvwfmy5dk021rg9x8yl6w2g3j0jjwbzx1bl9gdh0byrs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl";
      sha256 = "1k0fqfdylinb57s2aqwprahwbrsk3babg4gghz4g06hnlvky77ck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "2.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/03/ad9306a50d05c166e3456fe810f33cee2b8b2a7a6818ec5d4908c4ec6b36/urllib3-2.0.3-py3-none-any.whl";
      sha256 = "1lc30hyl8rsxs0jifvq9waphyd08n84nig719243b79i83xgmrs8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
